// Curated list of common English words (adjectives, nouns, verbs) used for Cloudflare Tunnel link simulation.
window.CLOUDFLARE_WORDS = [
  "wise", "juvenile", "pink", "recovered", "weak", "atm", "ways", "provides", "usually", "poor", "about", "above", "across",
  "act", "active", "actor", "add", "address", "adopt", "adult", "advice", "advise", "affect", "after", "again", "against",
  "age", "agency", "agent", "agree", "ahead", "aim", "air", "alarm", "album", "alcohol", "alert", "alike", "alive", "all",
  "allow", "almost", "alone", "along", "already", "also", "alter", "always", "amazing", "amount", "ancient", "anger",
  "angle", "angry", "animal", "annual", "another", "answer", "any", "apart", "appeal", "appear", "apple", "apply", "area",
  "argue", "arm", "army", "around", "arrange", "arrest", "arrival", "arrive", "art", "article", "artist", "aside", "ask",
  "aspect", "assault", "assert", "assess", "asset", "assume", "assure", "athlete", "atomic", "attach", "attack", "attain",
  "attempt", "attend", "attract", "audio", "audit", "august", "aunt", "author", "auto", "autumn", "avail", "average", "avoid",
  "award", "aware", "away", "awful", "baby", "back", "backup", "bacon", "bad", "badge", "bag", "bake", "balance", "ball",
  "balloon", "ballot", "banana", "band", "bank", "bar", "barrier", "base", "basic", "basis", "basket", "battery", "battle",
  "beach", "beacon", "beam", "bean", "bear", "beast", "beat", "beauty", "become", "bed", "beef", "beer", "before", "beg",
  "begin", "behalf", "behind", "behold", "being", "belief", "believe", "bell", "belong", "below", "belt", "bench", "bend",
  "beneath", "benefit", "berry", "beside", "best", "bet", "better", "between", "beyond", "bias", "bicycle", "bid", "big",
  "bike", "bill", "bind", "biology", "bird", "birth", "biscuit", "bishop", "bit", "bite", "bitter", "black", "blade",
  "blame", "blank", "blast", "blaze", "bleed", "blend", "bless", "blind", "blink", "block", "blond", "blood", "bloom",
  "blossom", "blow", "blue", "board", "boast", "boat", "body", "boil", "bold", "bolt", "bomb", "bond", "bone", "bonus",
  "book", "boom", "boost", "boot", "booth", "border", "bore", "borrow", "boss", "both", "bottle", "bottom", "bounce",
  "bound", "bounty", "bowl", "box", "boy", "brain", "brake", "branch", "brand", "brass", "brave", "bread", "break",
  "breast", "breath", "breathe", "breeze", "brick", "bridge", "brief", "bright", "brilliant", "bring", "brisk", "broad",
  "broken", "bronze", "brook", "broom", "brother", "brown", "brush", "bubble", "bucket", "buddy", "budget", "buffer",
  "bug", "build", "bulb", "bulk", "bullet", "bunch", "bundle", "burden", "bureau", "burn", "burst", "bus", "bush",
  "business", "busy", "but", "butter", "button", "buy", "buyer", "buzz", "cabin", "cable", "cactus", "cage", "cake",
  "calm", "camera", "camp", "campaign", "campus", "can", "canal", "cancel", "cancer", "candle", "candy", "cane",
  "canvas", "canyon", "cap", "cape", "capital", "captain", "caption", "car", "carbon", "card", "care", "career",
  "cargo", "carpet", "carriage", "carrot", "carry", "cart", "carve", "case", "cash", "casino", "cast", "castle",
  "casual", "cat", "catalog", "catch", "category", "cattle", "cause", "caution", "cave", "cavity", "cease", "cedar",
  "ceiling", "celebrate", "cell", "cement", "census", "center", "central", "century", "cereal", "certain", "chain",
  "chair", "chalk", "chamber", "champion", "chance", "change", "channel", "chaos", "chapter", "charge", "charity",
  "charm", "chart", "chase", "cheap", "cheat", "check", "cheek", "cheer", "cheese", "chef", "chemical", "cherry",
  "chess", "chest", "chicken", "chief", "child", "chili", "chill", "chimney", "chin", "chip", "choice", "choir",
  "choose", "chorus", "chronic", "chunk", "church", "cider", "cigar", "cinema", "circle", "circuit", "circus",
  "citizen", "city", "civic", "civil", "claim", "clam", "clan", "clarity", "clash", "clasp", "class", "classic",
  "clause", "claw", "clay", "clean", "clear", "clerk", "clever", "click", "client", "cliff", "climate", "climb",
  "cling", "clinic", "clip", "clock", "close", "cloth", "cloud", "clover", "clown", "club", "clump", "cluster",
  "clutch", "coach", "coal", "coast", "coat", "cobalt", "cobra", "coconut", "code", "coffee", "coffin", "cohort",
  "coil", "coin", "cold", "collar", "collect", "college", "colony", "color", "column", "combat", "combine",
  "come", "comedy", "comfort", "comic", "command", "comment", "commit", "common", "compact", "company", "compare",
  "compass", "compel", "compete", "comply", "compose", "compute", "concept", "concern", "concert", "concrete",
  "conduct", "conduit", "cone", "confer", "confess", "confirm", "conflict", "conform", "confuse", "congress",
  "connect", "consent", "conserve", "consider", "consist", "console", "constant", "consult", "consume", "contact",
  "contain", "content", "contest", "context", "continue", "contour", "contract", "contrary", "control", "convert",
  "convey", "convict", "cook", "cool", "cooperate", "cope", "copper", "copy", "coral", "cord", "core", "cork",
  "corn", "corner", "corona", "correct", "corridor", "cost", "costume", "cottage", "cotton", "couch", "cough",
  "could", "council", "counsel", "count", "country", "county", "couple", "courage", "course", "court", "cousin",
  "cove", "cover", "covet", "cow", "coward", "coyote", "crab", "crack", "cradle", "craft", "crag", "cram",
  "crane", "crash", "crate", "crater", "crave", "craw", "crawl", "crayon", "crazy", "cream", "create", "credit",
  "creed", "creek", "creep", "crescent", "crest", "crew", "cricket", "crime", "crisis", "crisp", "critic", "croft",
  "crop", "cross", "crouch", "crow", "crowd", "crown", "crude", "cruel", "cruise", "crumb", "crush", "crust",
  "crypt", "crystal", "cube", "cuckoo", "cucumber", "cuff", "cult", "culture", "cup", "curable", "curator",
  "curb", "cure", "curfew", "curia", "curio", "curious", "curl", "curly", "current", "curry", "curse", "curve",
  "cushion", "custody", "custom", "cute", "cycle", "cynic", "cypress", "daddy", "daily", "dairy", "daisy",
  "damage", "damp", "dance", "danger", "dare", "dark", "darling", "darn", "dart", "dash", "data", "date",
  "daughter", "dawn", "day", "dead", "deaf", "deal", "dean", "dear", "death", "debate", "debris", "debt",
  "debut", "decade", "decay", "decent", "decide", "decision", "deck", "declare", "decline", "decor", "decrease",
  "decree", "deduct", "deed", "deep", "deer", "defeat", "defend", "defense", "deficit", "define", "defy",
  "degree", "delay", "delegate", "delight", "deliver", "delta", "deluge", "demand", "demise", "demo", "demon",
  "denial", "denote", "dense", "dental", "depart", "depend", "depict", "deploy", "deposit", "depot", "depth",
  "deputy", "derby", "derive", "desert", "design", "desire", "desk", "pair", "peer", "relay", "tunnel",
  "destroy", "detail", "detect", "device", "devil", "devote", "dialog", "diamond", "diary", "dice", "dictate",
  "dictionary", "did", "die", "diet", "differ", "difficult", "dig", "digest", "digital", "dignity", "dilemma",
  "dill", "dilute", "dime", "diminish", "dine", "diner", "dingo", "dinner", "dinosaur", "diode", "dioxide",
  "direct", "dirt", "dirty", "disabled", "disagree", "disaster", "disc", "discharge", "discover", "discuss",
  "disease", "dish", "dislike", "dismiss", "disorder", "displace", "display", "disposal", "dispute", "disrupt",
  "dissolve", "distance", "distant", "distinct", "distort", "district", "distrust", "ditch", "dive", "diver",
  "divide", "divine", "divorce", "dizzy", "dock", "doctor", "document", "dodge", "dog", "doll", "dollar",
  "dolphin", "domain", "dome", "domestic", "dominant", "donate", "donkey", "donor", "door", "dose", "dot",
  "double", "doubt", "dough", "dove", "down", "dozen", "draft", "drag", "drain", "drake", "drama", "drastic",
  "draw", "drawer", "dream", "dredge", "drench", "dress", "drew", "drift", "drill", "drink", "drip", "drive",
  "driver", "drop", "drought", "drown", "drug", "drum", "dry", "dual", "duck", "duct", "due", "duel",
  "duet", "duke", "dull", "duly", "dumb", "dump", "dune", "dung", "dungeon", "duo", "duplicate", "durable",
  "duration", "dusk", "dust", "dusty", "duty", "dwarf", "dwell", "dye", "dying", "dynamic", "dynamite",
  "each", "eager", "eagle", "ear", "early", "earn", "earth", "ease", "east", "easy", "eat", "echo",
  "eclipse", "ecology", "economic", "economy", "edge", "edict", "edit", "editor", "educate", "eel", "effect",
  "effort", "egg", "ego", "eight", "either", "elastic", "elbow", "elder", "elect", "electron", "elegant",
  "element", "elephant", "elevate", "eleven", "elf", "elicit", "eligible", "elite", "elk", "ellipse",
  "elm", "eloquent", "else", "elude", "email", "embark", "embed", "emblem", "embrace", "emerge", "emission",
  "emit", "emotion", "emperor", "emphasis", "empire", "employ", "empty", "enable", "enact", "enamel",
  "enclave", "enclose", "encounter", "encourage", "end", "endure", "enemy", "energy", "enforce", "engage",
  "engine", "engineer", "english", "enhance", "enjoy", "enlarge", "enlist", "enormous", "enough", "enquire",
  "enroll", "ensue", "ensure", "entail", "enter", "enterprise", "entire", "entity", "entrance", "entry",
  "envelope", "environ", "envoy", "envy", "enzyme", "epic", "epoch", "equal", "equate", "equip", "equity",
  "era", "erase", "erect", "erosion", "error", "erupt", "escape", "escort", "essay", "essence", "estate",
  "esteem", "estimate", "etc", "eternal", "ether", "ethics", "ethnic", "euro", "evacuate", "evade",
  "evaluate", "even", "evening", "event", "ever", "every", "evidence", "evil", "evoke", "evolution",
  "evolve", "exact", "exalt", "exam", "exceed", "excel", "except", "excess", "exchange", "excite",
  "exclude", "excuse", "execute", "exempt", "exercise", "exert", "exhibit", "exile", "exist", "exit",
  "exotic", "expand", "expect", "expel", "expend", "expense", "expert", "expire", "explain", "explicit",
  "explode", "exploit", "explore", "export", "expose", "express", "extend", "extent", "exterior", "external",
  "extra", "extract", "extreme", "eye", "fabric", "face", "facility", "fact", "factor", "factory",
  "fade", "fail", "failure", "faint", "fair", "faith", "fake", "falcon", "fall", "false", "fame",
  "family", "famine", "famous", "fan", "fancy", "fang", "fantasy", "far", "fare", "farm", "farmer",
  "farthest", "fascinate", "fashion", "fast", "fatal", "fate", "father", "fatigue", "faucet", "fault",
  "favor", "favorite", "fawn", "fear", "feast", "feat", "feature", "federal", "fee", "feed", "feedback",
  "feel", "feet", "feign", "feline", "fell", "fellow", "felt", "female", "fence", "fender", "ferment",
  "fern", "ferry", "fertile", "fervent", "festival", "fetch", "feud", "fever", "few", "fiance", "fiber",
  "fiction", "fiddle", "field", "fierce", "fiery", "fifteen", "fifth", "fifty", "fig", "fight", "fighter",
  "figure", "file", "fill", "film", "filter", "filth", "final", "finance", "find", "fine", "finger",
  "finish", "finite", "fir", "fire", "firm", "first", "fish", "fissure", "fist", "fit", "fitness",
  "five", "fix", "fixture", "flag", "flair", "flake", "flame", "flank", "flare", "flash", "flask",
  "flat", "flavor", "flaw", "flax", "flee", "fleet", "flesh", "flew", "flex", "flick", "flight",
  "flim", "flinch", "fling", "flint", "flip", "flirt", "float", "flock", "flood", "floor", "flora",
  "flour", "flow", "flower", "flown", "flu", "flue", "fluent", "fluid", "fluke", "flume", "flush",
  "flute", "fly", "flyer", "foam", "focal", "focus", "fog", "foggy", "foil", "fold", "folder",
  "foliage", "folk", "follow", "folly", "fond", "food", "fool", "foot", "footage", "for", "forbid",
  "force", "ford", "fore", "foreign", "forest", "forge", "forget", "forgive", "fork", "form",
  "formal", "format", "former", "formula", "fort", "forth", "forty", "forum", "forward", "fossil",
  "foster", "fought", "foul", "found", "fountain", "four", "fourth", "fowl", "fox", "foyer",
  "fraction", "fracture", "fragile", "fragment", "frame", "franchise", "frank", "frantic", "fraud",
  "fray", "freak", "free", "freeze", "freight", "french", "frenzy", "frequent", "fresh", "fret",
  "friction", "friday", "fridge", "friend", "fright", "fringe", "frock", "frog", "from", "front",
  "frost", "froth", "frown", "frozen", "frugal", "fruit", "frustrate", "fry", "fudge", "fuel",
  "fugitive", "fulfill", "full", "fully", "fume", "fun", "function", "fund", "funeral", "fungus",
  "funnel", "funny", "fur", "furious", "furnace", "furnish", "furrow", "further", "fury", "fuse",
  "fusion", "fuss", "future", "fuzzy", "gadget", "gag", "gain", "gait", "gala", "galaxy",
  "gale", "gall", "gallery", "gallon", "gallop", "gallows", "gamut", "gap", "gape", "garage",
  "garbage", "garden", "gargle", "garlic", "garment", "garter", "gas", "gaseous", "gash", "gasp",
  "gate", "gateway", "gather", "gauge", "gaunt", "gauze", "gave", "gavel", "gawk", "gay",
  "gaze", "gear", "gel", "gem", "gender", "gene", "general", "generate", "generous", "genesis",
  "genial", "genius", "genre", "gentle", "genuine", "genus", "geology", "geometry", "germ", "gesture",
  "get", "geyser", "ghetto", "ghost", "giant", "gibber", "giddy", "gift", "gigantic", "giggle",
  "gild", "gill", "gimmick", "gin", "ginger", "girdle", "girl", "girth", "gist", "give",
  "given", "glacier", "glad", "glade", "gladiator", "glance", "gland", "glare", "glass", "glaze",
  "gleam", "glean", "glee", "glen", "glide", "glimmer", "glimpse", "glisten", "glitch", "glitter",
  "gloat", "globe", "gloom", "gloomy", "glory", "gloss", "glossary", "glove", "glow", "glue",
  "glum", "glut", "glycerin", "gnarl", "gnash", "gnat", "gnaw", "goad", "goal", "goat",
  "goblet", "goblin", "god", "goggles", "going", "gold", "golden", "golf", "gondola", "gone",
  "gong", "good", "goodbye", "goof", "goose", "gore", "gorge", "gorgeous", "gorilla", "gospel",
  "gossip", "got", "gourd", "govern", "gown", "grab", "grace", "grade", "gradient", "gradual",
  "graft", "grain", "gram", "grammar", "grand", "grandeur", "grange", "granite", "grant", "grape",
  "graph", "grasp", "grass", "grate", "grave", "gravel", "gravity", "gravy", "gray", "graze",
  "grease", "great", "greed", "greedy", "green", "greet", "grew", "grey", "grid", "grief",
  "grill", "grim", "grimace", "grime", "grin", "grind", "grip", "gripe", "grit", "grizzly",
  "groan", "grocer", "grocery", "groggy", "groin", "groom", "groove", "grope", "gross", "grotto",
  "grouch", "ground", "group", "grouse", "grove", "grow", "growl", "grown", "growth", "grub",
  "grudge", "gruel", "gruff", "grumble", "grunt", "guano", "guard", "guardian", "guava", "guerilla",
  "guess", "guest", "guffaw", "guidance", "guide", "guild", "guile", "guilt", "guilty", "guinea",
  "guise", "guitar", "gulch", "gulf", "gull", "gully", "gulp", "gum", "gun", "gurgle",
  "gush", "gust", "gut", "gutter", "gym", "gymnast", "gypsy", "gyro", "habit", "habitat",
  "hack", "hacksaw", "haddock", "haggard", "hail", "hair", "hairy", "hale", "half", "hall",
  "hallow", "halo", "halt", "halter", "halve", "hamlet", "hammer", "hammock", "hamper", "hand",
  "handbook", "handcuff", "handicap", "handle", "handsome", "handy", "hang", "hangar", "hanger", "hangover",
  "hanker", "hapless", "happen", "happy", "harass", "harbor", "hard", "hardship", "hardware", "hare",
  "hark", "harlot", "harm", "harmony", "harness", "harp", "harpoon", "harrow", "harry", "harsh",
  "harvest", "has", "hash", "hasp", "haste", "hasty", "hat", "hatch", "hatchet", "hate",
  "hatred", "haughty", "haul", "haunch", "haunt", "have", "haven", "havoc", "hawk", "hawthorn",
  "hay", "hazard", "haze", "hazel", "hazy", "head", "headache", "heading", "headquarters", "heal",
  "health", "healthy", "heap", "hear", "hearsay", "hearse", "heart", "hearth", "hearty", "heat",
  "heater", "heath", "heathen", "heave", "heaven", "heavy", "hectic", "hedge", "heed", "heel",
  "heft", "hefty", "heir", "held", "helium", "helix", "hello", "helm", "helmet", "help",
  "helpful", "helpless", "hem", "hemisphere", "hemlock", "hemp", "hen", "hence", "herald", "herb",
  "herd", "here", "hereafter", "hereby", "heritage", "hermit", "hero", "heroic", "heron", "herring",
  "herself", "hesitate", "hew", "hexagon", "hey", "heyday", "hickory", "hid", "hidden", "hide",
  "hideous", "hierarchy", "high", "highway", "hike", "hiker", "hilarious", "hill", "hilly", "hilt",
  "himself", "hind", "hinder", "hinge", "hint", "hip", "hire", "his", "hiss", "history",
  "hit", "hitch", "hive", "hoad", "hoar", "hoard", "hoarse", "hoary", "hobby", "hobo",
  "hockey", "hoe", "hog", "hoist", "hold", "holder", "hole", "holiday", "hollow", "holly",
  "holocaust", "holster", "holy", "homage", "home", "homely", "honest", "honey", "honor", "hood",
  "hoof", "hook", "hoop", "hoot", "hop", "hope", "hopeful", "hopeless", "horizon", "horn",
  "hornet", "horrible", "horror", "horse", "hose", "hospice", "hospital", "host", "hostage", "hostel",
  "hostile", "hot", "hotel", "hound", "hour", "house", "hovel", "hover", "how", "however",
  "howl", "hub", "huddle", "hue", "huff", "hug", "huge", "hulk", "hull", "hum",
  "human", "humane", "humble", "humid", "humor", "humorous", "hump", "humus", "hunch", "hundred",
  "hung", "hunger", "hungry", "hunt", "hunter", "hurdle", "hurl", "hurricane", "hurry", "hurt",
  "husband", "hush", "husk", "husky", "hustle", "hut", "hybrid", "hydrant", "hydrogen", "hyena",
  "hygiene", "hymn", "hyphen", "hypocrisy", "hypothesis", "hysteria", "ice", "icicle", "icing",
  "icon", "icy", "idea", "ideal", "identify", "identity", "idiom", "idiot", "idle", "idol",
  "if", "igloo", "ignite", "ignore", "ill", "illegal", "illness", "illusion", "illustrate", "image",
  "imagine", "imitate", "immense", "immerse", "immigrate", "impact", "impair", "impale", "impart", "impasse",
  "impeach", "impede", "impel", "impend", "imperil", "impetus", "impinge", "implant", "implement", "imply",
  "import", "impose", "imposing", "impossible", "impostor", "impound", "impoverish", "impress", "imprint", "imprison",
  "improbable", "improve", "impulse", "impunity", "impurity", "in", "inability", "inaccurate", "inactive", "inbound"
];
